version: '3'
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - appnetwork
    environment:
      MINIO_ROOT_USER: mmadmin
      MINIO_ROOT_PASSWORD: mmadmin2024
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

networks:
  appnetwork:
    driver: bridge

volumes:
  minio_data: {}
