version: '3'
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: 
      MINIO_ROOT_PASSWORD: 
    volumes:
      - minio_data:/data
    command: server /data

volumes:
  minio_data:
