services:
  postgres:
    container_name: postgres_db
    image: postgres:14
    environment:
      POSTGRES_USER: webadmin
      POSTGRES_PASSWORD: webadmin
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: